name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@main
      with:
        username: 'lljsss'
        reponame: 'article-backstage-vue3-elementPlus'
        token: ${{ secrets.ACCESS_TOKEN }}

